### ISSUE TITLE
How do I update upcoming events?

### ISSUE THREAD

**Issue by Urigo** [kevinsimper/copenhagen.community#17]

**Comment by kevinsimper** [comment]
Hey @Urigo 

Thanks for notifying, that was a mistake on my part as I have to redeploy the Google Cloud Functions. I should setup CI/CD to automatic do that.

I have redeployed it now and it will show up within 1 hour.

**Comment by kevinsimper** [comment]
It is updated and I will remember to update it in the future 😄 I have a plan of creating a graphql api instead of a file on Google Cloud Storage.
